modLoader="javafml"
loaderVersion="[51.0.33,)"
license="All Rights Reserved"

[[mods]]
modId="floridamod"
version="0.0.2"
displayName="Florida Mod"
authors="I'll deal with this later"
description='A mod about Florida'

[[dependencies.floridamod]]
modId="forge"
mandatory=true
versionRange="[51.0.33,)"
ordering="NONE"
side="BOTH"

[[dependencies.floridamod]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.21.1,1.22)"
ordering="NONE"
side="BOTH"
